import { Injectable, inject } from '@angular/core';
import {
  ApiClientService,
  ApiRequestError,
} from '../../../../../compartido/api-client/api-client.service';
import type {
  IListadoPacientes,
  IPaciente,
  IReniecResultado,
  RegistroPacientePayload,
} from '../../../../../compartido/tipos/api-tipos';
import type { IPacienteDatosAdicionales } from '../../../../../compartido/tipos/tipos';

export interface ActualizarPacientePayload {
  birthCountryId?: number;
  maternalSurname?: string;
  homeAddress?: string;
  originCountryId?: number;
  paternalSurname?: string;
  firstName?: string;
  secondName?: string;
  thirdName?: string;
  dateOfBirth?: string;
  documentNumber?: string;
  phone?: string;
  cellphone?: string;
  autoGenerated?: string;
  sexTypeId?: number;
  originId?: number;
  educationDegreeId?: number;
  maritalStatusId?: number;
  docIdentityId?: number;
  occupationTypeId?: number;
  homeCenterId?: number;
  fatherName?: string;
  motherName?: string;
  homeCountryId?: number;
  historyNumber?: number;
  birthCenterId?: number;
  originCenterId?: number;
  originDistrictId?: number;
  homeDistrictId?: number;
  birthDistrictId?: number;
  ethnicityId?: string;
  languageId?: number;
  email?: string;
  disabilityId?: number;
  incapacityId?: number;
  auditUserId?: number;
}

@Injectable({
  providedIn: 'root',
})
export class PacientesApiService {
  private apiClient = inject(ApiClientService);

  private static readonly RENIEC_TIMEOUT_MS = 30000;

  listar(params: string): Promise<IListadoPacientes> {
    return this.apiClient.request<IListadoPacientes>(
      `/api/v1/pacientes?${params}`,
    );
  }

  buscar(params: string): Promise<IPaciente[]> {
    return this.apiClient.request<IPaciente[]>(
      `/api/v1/pacientes/buscar?${params}`,
    );
  }

  consultarReniec(nroDocumento: string): Promise<IReniecResultado> {
    const promesa = this.apiClient.request<IReniecResultado>(
      `/api/v1/reniec/${encodeURIComponent(nroDocumento)}?operacion=completo`,
    );
    return Promise.race([
      promesa,
      new Promise<never>((_, reject) =>
        setTimeout(
          () =>
            reject(
              new ApiRequestError(
                'RENIEC_TIMEOUT',
                'RENIEC tardó demasiado en responder. Intente nuevamente o complete los datos manualmente.',
                0,
              ),
            ),
          PacientesApiService.RENIEC_TIMEOUT_MS,
        ),
      ),
    ]);
  }

  porDocumento(
    nroDocumento: string,
    idTipoDocIdentidad: number | string,
  ): Promise<IPaciente> {
    return this.apiClient.request<IPaciente>(
      `/api/v1/pacientes/por-documento?nroDocumento=${encodeURIComponent(nroDocumento)}&idTipoDocIdentidad=${idTipoDocIdentidad}`,
    );
  }

  registrar(payload: RegistroPacientePayload): Promise<IPaciente> {
    return this.apiClient.request<IPaciente>('/api/v1/pacientes', {
      method: 'POST',
      body: JSON.stringify(payload),
    });
  }

  actualizar(
    idPaciente: number | string,
    payload: ActualizarPacientePayload,
  ): Promise<IPaciente> {
    return this.apiClient.request<IPaciente>(
      `/api/v1/pacientes/${idPaciente}`,
      { method: 'PUT', body: JSON.stringify(payload) },
    );
  }

  eliminar(idPaciente: number | string): Promise<IPaciente> {
    return this.apiClient.request<IPaciente>(
      `/api/v1/pacientes/${idPaciente}`,
      { method: 'DELETE' },
    );
  }

  obtener(idPaciente: number | string): Promise<IPaciente> {
    return this.apiClient.request<IPaciente>(`/api/v1/pacientes/${idPaciente}`);
  }

  obtenerDatosAdicionales(
    idPaciente: number | string,
  ): Promise<IPacienteDatosAdicionales> {
    return this.apiClient.request<IPacienteDatosAdicionales>(
      `/api/v1/pacientes/${idPaciente}/datos-adicionales`,
    );
  }

  actualizarDatosAdicionales(
    idPaciente: number | string,
    payload: Partial<IPacienteDatosAdicionales>,
  ): Promise<IPacienteDatosAdicionales> {
    return this.apiClient.request<IPacienteDatosAdicionales>(
      `/api/v1/pacientes/${idPaciente}/datos-adicionales`,
      {
        method: 'PUT',
        body: JSON.stringify(payload),
      },
    );
  }
}
